version: '3.4'

services:
  signalrapi:
    image: ${DOCKER_REGISTRY-}signalrapi
    build:
      context: .
      dockerfile: SignalRAPI/Dockerfile
      
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"